# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 922d7dd1602451b29f23c50a4e029b6f1ba80ae194b21f5e217d2434322a638e992a16de870af8ea932a6368ce414b7a541b6f43979f27c2115a954866fbcaf6

test:
  secret_key_base: 6e04f833e7281c0f3cce9fc828d78e3e989abf5f8e4824a928375e36b36aead8565211f875d6b8d95144b303db0a9639e62336b2e7d51f9315b8e08cd893858c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
